---
- name: Install htpasswd utility
  apt:
    name: apache2-utils
    state: present

- name: Ensure that the {{ container_name }} container is created and running
  docker_container:
    name: "{{ container_name }}"
    image: lykhee/fava-docker:latest
    state: started
    pull: yes
    restart: yes
    restart_policy: unless-stopped
    env:
     "BEANCOUNT_FILE": "/bean/data/master.beancount"
    volumes:
      - "{{ beancount_data }}:/bean/data"
      - "{{ docker_dir }}/{{ container_name }}/config:/bean/config"

- name: Ensure that the {{ container_name }}-auth container does not exist
  docker_container:
    name: "{{ container_name }}-auth"
    state: absent

- name: Create the {{ container_name }}-auth container
  docker_container:
    name: "{{ container_name }}-auth"
    image: beevelop/nginx-basic-auth:latest
    state: started
    pull: yes
    restart_policy: unless-stopped
    ports:
      - "8089:8089"
    env:
      "FORWARD_PORT": "5000"
      "FORWARD_HOST": "{{ container_name }}"
      "HTPASSWD": "{{ htpasswd }}"
    links:
      - "{{ container_name }}:{{ container_name }}"

- name: Run command to change listen port
  community.docker.docker_container_exec:
    container: "{{ container_name }}-auth"
    command: sed -i 's/listen 80/listen 8089/' auth.conf 
    chdir: /opt

- name: Restart {{ container_name }}-auth container
  docker_container:
    name: "{{ container_name }}-auth"
    restart: yes

- name: Check if prices.beancount exists
  stat:
    path: "{{ beancount_data }}/prices.beancount"
  tags: cron
  register: prices_file

- name: Create cron job at 19:00 daily to fetch new beancount prices
  ansible.builtin.cron:
    name: "Fetch Beancount Prices"
    user: "{{ username }}"
    minute: "0"
    hour: "19"
    job: "docker exec fava bean-price /bean/data/master.beancount  >> {{ beancount_data }}/prices.beancount"
  tags: cron
  when: prices_file.stat.exists

- name: Check if queries directory and files exists
  stat:
    path: "{{ beancount_data }}/queries/{{ item }}"
  with_items:
    - query.sh
    - update_budget.sh
    - is_monthly_bals
  tags: cron
  register: query_results

- name: Create cron job at 06:00 daily to export is_monthly_bals query data and Update budget worksheet
  ansible.builtin.cron:
    name: "Export is_monthly_bals query data and Update budget worksheet"
    user: "{{ username }}"
    minute: "0"
    hour: "6"
    job: "bash {{ beancount_data }}/queries/query.sh -q is_monthly_bals -s 2021-11-01 && bash {{ beancount_data }}/queries/update_budget.sh"    
  tags: cron
  when: 
    - query_results.results[0].stat.exists
    - query_results.results[1].stat.exists
    - query_results.results[2].stat.exists