---
- name: Make sure the {{ container_name }} container is created and running
  docker_container:
    name: "{{ container_name }}"
    image: "ghcr.io/linuxserver/wireguard"
    pull: yes
    restart: yes
    privileged: yes
    sysctls:
      "net.ipv4.conf.all.src_valid_mark": "1"
    capabilities: 
      - net_admin
      - sys_module
    state: 'started'
    env:
      PUID="{{ ansible_user_uid }}"
      PGID="{{ ansible_user_gid }}"
      TZ="{{ timezone }}"
      SERVERURL="{{ duckdns_domain }}.duckdns.org"
      SERVERPORT="51820"
      PEERS="{{ ', '.join(wireguard_peers) }}"
      ALLOWEDIPS="0.0.0.0/0"
      PEERDNS="{{ pi_hole }}"
    ports:
      - "51820/udp:51820/udp"
    volumes:
      - "{{ docker_dir }}/{{ container_name }}/config:/config"
      - "/lib/modules:/lib/modules"
    restart_policy: unless-stopped