---
- name: Set the hostname
  hostname:
    name: "{{ inventory_hostname }}"

- name: Update and upgrade apt packages (Debian and Ubuntu)
  when: ansible_os_family == 'Debian'
  shell:
    cmd: apt update && apt upgrade -y

- name: Installing packages
  apt:
    name: '{{ item }}'
    state: present
    update_cache: True
  with_items:
    - git
    - vim

- name: Ensure fstrim.timer is enabled 
  ansible.builtin.systemd:
    state: started
    name: fstrim.timer

- name: Copy the host's public SSH key to the remote server
  become: no
  authorized_key:
    user: "{{ username }}"
    state: present
    key: "{{ lookup('file', '/Users/' + lookup('env', 'USER') + '/.ssh/id_rsa.pub') }}"

- name: Check swap size
  shell: grep -E "CONF_SWAPSIZE=100" /etc/dphys-swapfile || echo false
  register: grep_output

- name: Disable Swap
  shell: dphys-swapfile swapoff
  when: grep_output.stdout != "false"

- name: Change swap size to 4gb
  shell: sed -i 's/CONF_SWAPSIZE=100/CONF_SWAPSIZE=4096/g'
  when: grep_output.stdout != "false"

- name: Initialise Swap File
  shell: dphys-swapfile setup
  when: grep_output.stdout != "false"

- name: Start Swap
  shell: dphys-swapfile swapon
  when: grep_output.stdout != "false"

# add arm_64bit=1 under pi /boot/config.txt

# reboot