---
- hosts: pve
  become: yes
  become_user: "{{ ansible_user }}"
  become_method: "sudo"

  roles:

    # Initial set-up of system
    - role: bootstrap
    - role: docker

    # Enable Duck DNS
    - role: duckdns
      when: enable_duckdns | default(False)
      tags: 
        - duckdns
        - cron

    #
    # Docker Services Start
    #
    
    - role: containers/portainer

    - role: containers/nginx
      when: enable_nginx | default(False)
      tags: 
        - nginx
        - containers

    - role: containers/wireguard
      when: enable_wireguard | default(False)
      tags: 
        - wireguard
        - containers

    - role: containers/homeassistant
      when: enable_homeassistant | default(False)
      tags: 
        - homeassistant
        - containers

    - role: containers/snippetbox
      when: enable_snippetbox | default(False)
      tags: 
        - snippetbox
        - containers

    - role: containers/flame
      when: enable_flame | default(False)
      tags: 
        - flame
        - containers

    #
    # Docker Services End
    #

    - role: nfs
      when: enable_nfs | default(False)
      tags:
        - nfs

    - role: filesystem/rclone
      when: enable_rclone | default(False)
      tags:
        - rclone