---
- hosts: pve
  become: yes

  roles:

    # Initial set-up of system
    - role: bootstrap
    - role: docker

    # Enable Duck DNS
    - role: duckdns
      when: enable_duckdns | default(False)
      tags: 
        - duckdns
        - cron

    # Docker containers
    - role: containers/portainer

    - role: containers/nginx
      when: enable_nginx | default(False)
      tags: 
        - nginx
        - containers

    - role: containers/flame
      when: enable_flame | default(False)
      tags: 
        - flame
        - containers