---
- hosts: khazpie
  become: yes
  
  roles:
    - role: essentials
      tags:
        - essentials

    - role: filesystem/mount
      tags:
        - mount
    
    - role: chriswayg.msmtp-mailer
      tags: 
        - msmtp

    - role: samba
      when: enable_samba | default(False)
      tags: 
        - samba

    - role: duckdns
      when: enable_duckdns | default(False)
      tags: 
      - duckdns
      - cron

    - role: containers/nginx
      when: enable_nginx | default(False)
      tags: 
      - nginx
      - containers

    - role: containers/homer
      when: enable_homer | default(False)
      tags: 
      - homer
      - containers

    - role: containers/resilio
      when: enable_resilio | default(False)
      tags: 
      - resilio
      - containers

    - role: containers/unifi
      when: enable_unifi | default(False)
      tags: 
      - unifi
      - containers

    - role: containers/adguard
      when: enable_adguard | default(False)
      tags: 
      - adguard
      - containers

    - role: containers/portainer
      when: enable_portainer | default(False)
      tags: 
      - portainer
      - containers

    - role: containers/homeassistant
      when: enable_homeassistant | default(False)
      tags: 
        - homeassistant
        - containers

    - role: containers/photoprism
      when: enable_photoprism | default(False)
      tags: 
        - photoprism
        - containers

    - role: containers/airsonic
      when: enable_airsonic | default(False)
      tags: 
        - airsonic
        - containers

    - role: containers/beancount
      when: enable_beancount | default(False)
      tags: 
        - beancount
        - containers

    - role: containers/beets
      when: enable_beets | default(False)
      tags: 
        - beets
        - containers

    - role: containers/rpimonitor
      when: enable_rpimonitor | default(False)
      tags: 
        - rpimonitor
        - containers

    - role: garminexport
      when: enable_garminexport | default(False)
      become: no
      tags:
        - garminexport

    - role: stefangweichinger.ansible_rclone
      when: enable_timemachine | default(False)
      tags:
        - rclone

    - role: filesystem/timemachine
      when: enable_timemachine | default(False)
      tags: 
        - timemachine