
---
- hosts: khazpie
  become: yes
  
  roles:
    - role: chriswayg.msmtp-mailer
      tags: 
        - msmtp

    - role: duckdns
      when: enable_duckdns | default(False)
      become: no
      tags: 
      - duckdns
      - cron

    - role: containers/homeassistant
      when: enable_homeassistant | default(False)
      tags: 
        - homeassistant
        - containers
      
    - role: timemachine
      when: enable_timemachine | default(False)
      tags: 
        - timemachine
        - cron