---
- hosts: khazpie
  become: yes
  
  roles:
    - role: filesystem/mount
      tags:
        - mount
    
    - role: chriswayg.msmtp-mailer
      tags: 
        - msmtp

    - role: samba
      when: enable_samba | default(False)
      tags: 
        - samba

    - role: duckdns
      when: enable_duckdns | default(False)
      tags: 
      - duckdns
      - cron

    - role: containers/adguard
      when: enable_adguard | default(False)
      tags: 
      - adguard

    - role: containers/homeassistant
      when: enable_homeassistant | default(False)
      tags: 
        - homeassistant
        - containers

    - role: containers/photoprism
      when: enable_photoprism | default(False)
      tags: 
        - photoprism
        - containers

    - role: containers/beancount
      when: enable_beancount | default(False)
      tags: 
        - beancount
        - containers

    - role: stefangweichinger.ansible_rclone
      when: enable_timemachine | default(False)
      tags:
        - rclone

    - role: filesystem/timemachine
      when: enable_timemachine | default(False)
      tags: 
        - timemachine