---
- name: Ensure that the {{ container_name }} container is created and running
  docker_container:
    name: "{{ container_name }}"
    image: jacobalberty/unifi:latest
    state: started
    pull: yes
    restart: yes
    restart_policy: unless-stopped
    network_mode: host
    env:
      "TZ": "{{ timezone }}"
      "RUNAS_UID0": "false"
      "UNIFI_UID": "{{ uid }}"
      "UNIFI_GID": "{{ uid }}"
    volumes:
      - "{{ docker_dir }}/{{ container_name }}:/unifi"