
# [pve:vars]

#
# Packages
#

extra_packages:
  - qemu-guest-agent
  - pip
  - git
  - vim

extra_pip:
  - glances
  - pyyaml
  - docker

#
# NFS Shares
#

# nfs_shares:
#   - path: "/nfs_share"

#
# Rclone
#

enable_rclone: true

rclone_config_location: "{{ ansible_user_dir }}/.config/rclone/rclone.conf"

# Services

enable_duckdns: true

enable_flame: true

enable_homeassistant: true

enable_nfs: true

enable_nginx: true

enable_snippetbox: true