version: '3.5'

services:
  fava:
    image: lykhee/fava-docker:latest
    container_name: fava
    restart: unless-stopped
    environment:
      BEANCOUNT_FILE: /bean/master.beancount
    volumes:
      - /mnt/pointer/bean:/bean

  fava-auth:
    image: beevelop/nginx-basic-auth:latest
    container_name: fava-auth
    restart: unless-stopped
    ports:
      - 8089:8089
    environment:
      FORWARD_PORT: 5000
      FORWARD_HOST: fava
      HTPASSWD: 'foo:$apr1$odHl5EJN$KbxMfo86Qdve2FH4owePn.'
    links:
      - fava:fava
