---
- name: Ensure that the {{ container_name }} container is created and running
  docker_container:
    name: "{{ container_name }}"
    image: pawelmalak/snippet-box:latest
    state: started
    pull: yes
    restart: yes
    restart_policy: unless-stopped
    volumes:
      - "{{ docker_dir }}/{{ container_name }}:/app/data"
    # ports: 
    #   - "5000:5000"
    # labels:
    #   "flame.type": "application"
    #   "flame.name": "{{ dashboard_name }}"
    #   "flame.url": "{{ dashboard_url }}"
    #   "flame.icon": "{{ dashboard_icon }}"