
---

- name: Check if config_dir exists
  stat:
    path: /home/{{ ansible_ssh_user }}/apps/adguard/
  register: config_dir

- ansible.builtin.debug:
    var: config_dir.stat.exists

- name: Deploy docker container
  docker_container:
    name: adguard
    image: adguard/adguardhome
    state: started
    pull: yes
    restart: yes
    restart_policy: unless-stopped
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 80:80/tcp
      - 3000:3000/tcp
    volumes:
      - /home/{{ ansible_ssh_user }}/apps/adguard/workdir:/opt/adguardhome/work
      - /home/{{ ansible_ssh_user }}/apps/adguard/confdir:/opt/adguardhome/conf
    container_default_behavior: compatibility
