---
- name: Check if PiVPN is already installed
  stat: path=/usr/local/bin/pivpn
  register: pivpn

- name: Install PiVPN
  block:
  - name: Copy options.conf to pivpn setup directory
    template:
      src: options.conf.j2
      dest: "/tmp/options.conf"
      mode: '0755'
      force: yes

  - name: Download PiVPN install.sh
    get_url:
      url: https://install.pivpn.io
      dest: /tmp/install.sh
      mode: '0755'
      force: yes

  - name: Install PiVPN with pre-configured options
    shell:
      cmd: ./install.sh --unattended options.conf
      chdir: /tmp/

  - name: Check if reboot required
    stat:
      path: /var/run/reboot-required
    register: reboot_required_file

  - name: Reboot if required
    reboot:
      msg: Rebooting due to a kernel update
    when: reboot_required_file.stat.exists == true
  when: not pivpn.stat.exists