---
- name: Ensure that the {{ container_name }} container is created and running
  docker_container:
    name: "{{ container_name }}"
    image: adguard/adguardhome
    state: started
    pull: yes
    restart: yes
    restart_policy: unless-stopped
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 80:80/tcp
      - 3000:3000/tcp
    volumes:
      - "{{ docker_dir }}/{{ container_name }}/workdir:/opt/adguardhome/work"
      - "{{ docker_dir }}/{{ container_name }}/confdir:/opt/adguardhome/conf"
    container_default_behavior: compatibility
