---
- name: Ensure that the {{ container_name }} container is created and running
  docker_container:
    name: "{{ container_name }}"
    image:  ghcr.io/linuxserver/beets
    state: started
    pull: yes
    restart: yes
    restart_policy: unless-stopped
    ports:
      - "8337:8337"
    env:
      "TZ": "{{ timezone }}"
      "PUID": "false"
      "PGID": "{{ uid }}"
    volumes:
      - "{{ docker_dir }}/{{ container_name }}:/config"
      - "{{ pointer_root }}/Music:/music"
      - "{{ pointer_root }}/Downloads:/downloads"