---
- name: Ensure that the {{ container_name }} container is created and running
  docker_container:
    name: "{{ container_name }}"
    image:  portainer/portainer-ce:latest
    state: started
    pull: yes
    restart: yes
    restart_policy: unless-stopped
    ports:
      - "8000:8000"
      - "9000:9000"      
    volumes:
      - "{{ docker_dir }}/{{ container_name }}:/data"
      - "/var/run/docker.sock:/var/run/docker.sock"