
---

- name: Install htpasswd utility
  package:
    name: apache2-utils
    state: present
  tags: packages, beancount

- name: Copy docker-compose.yml to remote folder
  copy:
    src: docker-compose.yml
    dest: /home/{{ ansible_ssh_user }}/docker_configs/beancount/
    owner: '{{ ansible_ssh_user }}'
    group: '{{ ansible_ssh_user }}'
    mode: '644'
  tags: beancount

- name: Tear down existing beancount docker services
  community.docker.docker_compose:
    project_src: /home/{{ ansible_ssh_user }}/docker_configs/beancount/
    state: absent
  tags: beancount

- name: Run `docker-compose up`
  community.docker.docker_compose:
    project_src: /home/{{ ansible_ssh_user }}/docker_configs/beancount/
    build: no
  register: output
  tags: beancount

- ansible.builtin.debug:
    var: output
  tags: beancount

- name: Run command to change listen port
  community.docker.docker_container_exec:
    container: fava-auth
    command: sed -i 's/listen 80/listen 8089/' auth.conf 
    chdir: /opt
  register: result
  tags: beancount

- name: Stop beancount docker services
  community.docker.docker_compose:
    project_src: /home/{{ ansible_ssh_user }}/docker_configs/beancount/
    build: no
    stopped: yes
  register: output
  tags: beancount

- ansible.builtin.debug:
    var: output
  tags: beancount

- name: Restart beancount docker services
  community.docker.docker_compose:
    project_src: /home/{{ ansible_ssh_user }}/docker_configs/beancount/
    build: no
    restarted: yes
  register: output
  tags: beancount

- ansible.builtin.debug:
    var: output
  tags: beancount
