---
- name: Ensure that the {{ container_name }} container is up-to-date and running
  docker_container:
    name: 'pihole'
    image: "cbcrowe/pihole-unbound"
    hostname: "{{ inventory_hostname }}"
    pull: true
    state: 'started'
    env:
      "ServerIP": "{{ ansible_default_ipv4.address }}"
      "TZ": "{{ timezone }}"
      "WEBPASSWORD": "{{ pihole_password }}"
      "DNS1": "127.0.0.1#5335" # Hardcoded to our Unbound server
      "DNS2": "127.0.0.1#5335" # Hardcoded to our Unbound server
      "DNSSEC": "false" # False - handled by our Unbound server
      "REV_SERVER": "true" # Enable conditional forwarding
      "REV_SERVER_DOMAIN": "home"
      "REV_SERVER_TARGET": "{{ ansible_default_ipv4.gateway }}"
      "REV_SERVER_CIDR": "{{ '.'.join(ansible_default_ipv4.address.split('.')[0:3]) }}.0/24"
      "DOMAIN_NAME": "pihole.home"
    volumes:
      - "{{ docker_dir }}/{{ container_name }}/pihole:/etc/pihole"
      - "{{ docker_dir }}/{{ container_name }}/dnmasq-unbound:/etc/dnsmasq.d"
    ports:
      - 443:443/tcp
      - 53:53/tcp
      - 53:53/udp
      - 80:80/tcp
    restart_policy: unless-stopped
    labels:
      "flame.type": "application"
      "flame.name": "{{ dashboard_name }}"
      "flame.url": "{{ dashboard_url }}"
      "flame.icon": "{{ dashboard_icon }}"