---
- name: Check if {{ scripts_dir }}/rclone_bkup directory exists
  stat:
    path: "{{ scripts_dir }}/rclone_bkup"
  register: config_dir

- name: Create {{ scripts_dir }}/rclone_bkup directory if it doesn't already exist
  file:
    path: "{{ scripts_dir }}/rclone_bkup"
    state: directory
    owner: "{{ ansible_user }}"
    mode: "0755"
  when: not config_dir.stat.exists

- name: Get scripts from repo
  ansible.builtin.git:
    repo: "https://github.com/kstockk/rclone-backup.git"
    dest: "{{ scripts_dir }}/rclone_bkup"
    update: yes
    force: yes
  become: no
  tags: pull

- name: Create rclone backups
  cron:
    name: "{{ item.name }}"
    hour: "{{ item.hour }}"
    minute: "{{ item.minute }}"
    job: 'sudo {{ scripts_dir }}/rclone_bkup/rclone-backup.sh "{{ item.src }}" "{{ item.dest }}"'
  with_items:
    - "{{ rclone_backups }}"
  become: no
  when: rclone_backups is defined
  tags: cron