# ---
# - name: Change rclone_config ownership and group
#   file:
#     path: "{{ rclone_config_location }}"
#     owner: "{{ username }}"
#     group: "{{ username }}"

- name: Create rclone_bkup directory
  file:
    path: "{{ scripts_dir }}/rclone_bkup"
    state: directory
    mode: "755"

- name: Copy rclone_bkup.sh to rclone_bkup directory
  copy:
    src: rclone_bkup.sh
    dest: "{{ scripts_dir }}/rclone_bkup/rclone_bkup.sh"
    mode: "755"

- name: Copy rclone_sync.sh to rclone_bkup directory
  copy:
    src: rclone_sync.sh
    dest: "{{ scripts_dir }}/rclone_bkup/rclone_sync.sh"
    mode: "755"

- name: Copy exclude-file.txt to rclone_bkup directory
  copy:
    src: exclude-file.txt
    dest: "{{ scripts_dir }}/rclone_bkup/exclude-file.txt"
    mode: "755"

- name: Create rclone backups
  cron:
    name: "{{ item.name }}"
    hour: "{{ item.hour }}"
    minute: "{{ item.minute }}"
    job: 'sudo {{ scripts_dir }}/rclone_bkup/rclone_bkup.sh "{{ item.src }}" "{{ item.dest }}"'
  with_items:
    - "{{ rclone_backups }}"
  become: no