
---

- name: Set Facts
  set_fact:
    repo: deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian buster stable
  when: ansible_architecture == "x86_64"

- name: Set Facts
  set_fact:
    repo: deb [arch=armhf signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian buster stable
  when: ansible_architecture == "aarch64"

- name: Install Prerequisites
  package:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - software-properties-common
      - libssl-dev
      - libffi-dev
      - python3
      - python3-pip
      - python3-venv
      - python-setuptools
    state: present
  tags: packages, docker

- name: Add Docker’s official GPG key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present
    keyring: /usr/share/keyrings/docker-archive-keyring.gpg
  tags: docker

- name: Add Docker Stable Repository
  apt_repository:
    repo: '{{ repo }}'
    state: present
    filename: docker
    update_cache: yes
  tags: docker

- name: Install Docker Engine 
  package:
    name: 
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: latest
    update_cache: yes
  tags: packages, docker

- name: Add the current user to the group 'docker'
  ansible.builtin.user:
    name: '{{ ansible_ssh_user }}'
    shell: /bin/bash
    groups: docker
    append: yes
  tags: docker

- name: Enable and start Docker service
  systemd:
    name: docker.service
    enabled: true
    state: started
  tags: docker

- name: Install docker-compose
  pip:
    name: 
      - docker-compose
    executable: pip3
  tags: docker, pip
