---

- name: Set Facts
  set_fact:
    repo: deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable
  when: ansible_architecture == "x86_64"
  tags: docker

- name: Set Facts
  set_fact:
    repo: deb [arch=armhf signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable
  when: ansible_architecture == "aarch64"
  tags: docker

- name: Install Prerequisites
  apt:
    name: '{{ packages }}'
    state: present
  vars:
    packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - software-properties-common
      - libssl-dev
      - libffi-dev
      - python3
      - python3-pip
      - python3-venv
      - python-setuptools
  tags: docker

- name: Add Docker's official GPG key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present
    keyring: /usr/share/keyrings/docker-archive-keyring.gpg
  tags: docker

- name: Add Docker Stable Repository
  apt_repository:
    repo: '{{ repo }}'
    state: present
    filename: docker
    update_cache: yes
  tags: docker

- name: Install Docker Engine 
  apt:
    name: '{{ packages }}'
    state: present
  vars:
    packages:
      - docker-ce
      - docker-ce-cli
      - containerd.io
  tags: docker

- name: Add 'pi' user to the group 'docker'
  ansible.builtin.user:
    name: pi
    shell: /bin/bash
    groups: docker
    append: yes
  tags: docker

- name: Give permissions to /var/run/docker.sock
  file:
    path: /var/run/docker.sock
    mode: '660'
  tags: docker

- name: Enable and start Docker service
  systemd:
    name: docker.service
    enabled: true
    state: started
  tags: docker

- name: Install docker-compose
  pip:
    name: 
      - cryptography==2.8
      - docker-compose
    executable: pip3
  tags: docker
