---
- name: Ensure that the {{ container_name }} network is created and running
  docker_network:
    name: "{{ container_name }}"

- name: Ensure that the {{ container_name }} MariaDB container is created and running
  docker_container:
    name: "photoprism-mariadb"
    image: "arm64v8/mariadb:10.5"
    pull: yes
    command: "mysqld --transaction-isolation=READ-COMMITTED --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max-connections=512 --innodb-rollback-on-timeout=OFF --innodb-lock-wait-timeout=50"
    state: 'started'
    env:
      "MYSQL_ROOT_PASSWORD": "{{ mysql_root_password }}"
      "MYSQL_DATABASE": "{{ mysql_db }}"
      "MYSQL_USER": "{{ mysql_user }}"
      "MYSQL_PASSWORD": "{{ mysql_password }}"
    volumes:
      - "{{ docker_dir }}/{{ container_name }}/database:/var/lib/mysql"
    restart_policy: unless-stopped
    security_opts:
      - seccomp:unconfined
      - apparmor:unconfined
    networks:
      - name: "{{ container_name }}"

- name: Ensure that the {{ container_name }} container is created and running
  docker_container:
    name: "{{ container_name }}"
    image: photoprism/photoprism
    pull: yes
    ports: 
      - "2342:2342"
    security_opts:
      - seccomp:unconfined
      - apparmor:unconfined
    state: 'started'
    env:
      "PHOTOPRISM_ADMIN_PASSWORD": "{{ admin_password }}"
      "PHOTOPRISM_ORIGINALS_LIMIT": "5000"
      "PHOTOPRISM_HTTP_COMPRESSION": "gzip"
      "PHOTOPRISM_WORKERS": "2"
      "PHOTOPRISM_DEBUG": "false"
      "PHOTOPRISM_PUBLIC": "false"
      "PHOTOPRISM_READONLY": "false"
      "PHOTOPRISM_EXPERIMENTAL": "false"
      "PHOTOPRISM_DISABLE_WEBDAV": "false"
      "PHOTOPRISM_DISABLE_SETTINGS": "false"
      "PHOTOPRISM_DISABLE_TENSORFLOW": "false"
      "PHOTOPRISM_DARKTABLE_PRESETS": "true"
      "PHOTOPRISM_DETECT_NSFW": "false"
      "PHOTOPRISM_UPLOAD_NSFW": "true"
      "PHOTOPRISM_DATABASE_DRIVER": "mysql"
      "PHOTOPRISM_DATABASE_SERVER": "photoprism-mariadb:3306"
      "PHOTOPRISM_DATABASE_NAME": "{{ mysql_db }}"
      "PHOTOPRISM_DATABASE_USER": "{{ mysql_user }}"
      "PHOTOPRISM_DATABASE_PASSWORD": "{{ mysql_password }}"
      "PHOTOPRISM_SITE_URL": "http://localhost:2342/"
      "PHOTOPRISM_SITE_TITLE": "PhotoPrism"
    volumes:
      - "{{ pointer_root }}/Pictures/photoprism:/photoprism/originals"
      - "{{ pointer_root }}/Pictures/import:/photoprism/import"
      - "{{ pointer_root }}/Pictures/photoprism_storage:/photoprism/storage"
      - "{{ docker_dir }}/{{ container_name }}/cache:/photoprism/storage/cache"
    restart_policy: unless-stopped
    networks:
      - name: "{{ container_name }}"
    labels:
      "flame.type": "application"
      "flame.name": "{{ dashboard_name }}"
      "flame.url": "{{ dashboard_url }}"
      "flame.icon": "{{ dashboard_icon }}"