dependencies:
  - role: geerlingguy.docker
    when: ansible_architecture != "aarch64"
    become: yes
    become_user: root
  - role: geerlingguy.docker_arm
    when: ansible_architecture == "aarch64"
    become: yes
    become_user: root